[workspace]
members = [
  "zwaves_primitives",
  "zwaves_circuit",
  "zwaves_jni",
  "sapling-crypto",
  "zwaves_setup",
  "zwaves_node/native"
]

[profile.release]
lto = true
panic = 'abort'
codegen-units = 1

[profile.dev]
lto = true
panic = 'abort'
codegen-units = 8
