[package]
name = "zwaves_primitives"
version = "0.1.0"
authors = ["Igor Gulamov <igor.gulamov@gmail.com>"]
edition = "2018"

[lib]
crate-type = ["rlib"]

[dependencies]
rand = "0.4"
bellman = { version = "0.1.0", default-features = false }
sapling-crypto = { git = "https://github.com/zcash-hackworks/sapling-crypto", rev = "21084bde2019c04bd34208e63c3560fe2c02fb0e", default-features = false }
pairing = "0.14"



